### PR TITLE
Include stddef.h for ptrdiff_t

### PR DESCRIPTION
**Pull request by nemequ**
Without this I get errors about ptrdiff_t being undefined.

### CODE REVIEW

**Comment by ConorStokes** [comment]
Out of curiosity, which compiler/standard library gave you this error? Definitely can see why it happened, although most implementations pull it in through the other headers.

**Comment by nemequ** [comment]
GCC 5.3.1 / glibc 2.22 (on Fedora 23 x86_64).

**Comment by ConorStokes** [comment]
Thanks, should be merged. Will watch out for that in future.

**Comment by ConorStokes** [comment]
Also, just be aware gcc currently lags Visual Studio and Clang performance wise for the decompression code by over 10%. It is on my to do list to work out what is causing it.

**Comment by nemequ** [comment]
ARM support is critical for me, so I'm not even considering actually using LZSSE for anything right now…  just putting together a plugin for [Squash](https://quixdb.github.io/squash/) (it should pop up in the new [squash-plugins-extra repository](https://github.com/quixdb/squash-plugins-extra) soon).

Just to give you fair warning: LZSSE will *probably* be included in the next version of the [Squash Benchmark](https://quixdb.github.io/squash-benchmark/), where it will be compiled with GCC.

**Pull request merged**
